spring.application.name=moeda-estudantil

spring.datasource.url=jdbc:postgresql://dpg-d8u3ljrtqb8s73aq91tg-a.oregon-postgres.render.com:5432/moeda_estudantil_sjsm
spring.datasource.username=moeda_estudantil_sjsm_user
spring.datasource.password=wHZ9EhoKMEEbmzMgqXSAWb2UHoiXXX0U
spring.datasource.driver-class-name=org.postgresql.Driver


# Dialeto do Banco
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}
spring.rabbitmq.ssl.enabled=true

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moedaestudantil56@gmail.com
spring.mail.password=bglh ywwg mmlp ttam
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true