spring.application.name=moeda-estudantil

# Banco de Dados (Use variáveis de ambiente!)
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8u3ljrtqb8s73aq91tg-a.oregon-postgres.render.com:5432/moeda_estudantil_sjsm}
spring.datasource.username=${DB_USERNAME:moeda_estudantil_sjsm_user}
spring.datasource.password=${DB_PASSWORD:wHZ9EhoKMEEbmzMgqXSAWb2UHoiXXX0U}
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# RabbitMQ (Já está ótimo com variáveis)
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}
spring.rabbitmq.ssl.enabled=true

# Email (Atenção: Remova a senha fixa daqui!)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moedaestudantil56@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# URL do frontend
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

# CORS
app.cors.allowed-origins=${APP_CORS_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,http://localhost,http://127.0.0.1}