@startuml Diagrama de Implantacao - Meritum_Enterprise

skinparam style strictuml
skinparam componentStyle uml2

skinparam node {
    BackgroundColor #F8F9FA
    BorderColor #495057
}

node "Client Tier (Dispositivo do Usuário)" #FFFFFF {
    component [Navegador Web / Mobile] as Browser
}

node "Edge Delivery: Vercel (CDN)" #LightBlue {
    artifact "SPA (React Bundle)" as SPA
    interface "HTTP/HTTPS" as CDN_IF
}

node "Platform Tier: Render (Cloud PAAS)" #LightGreen {
    node "Container Cluster (Backend)" {
        component "Spring Boot API Service" as API
        component "Resgate Background Worker" as Worker
    }
    
    node "Persistence Tier" {
        database "PostgreSQL Managed Instance" as DB
        note right of DB: Schema: \n- users\n- transactions\n- exchanges\n- coupons
    }
}

node "Messaging Tier: CloudAMQP" #LightGray {
    queue "vantagens.resgate.queue" as Fila
    note top of Fila: RabbitMQ (AMQP 0.9.1)
}

node "External Service Integration" #F5F5F5 {
    component "ViaCEP REST API" as ViaCEP
}

Browser --> CDN_IF : Acesso (DNS/HTTPS)
CDN_IF --> SPA : Serve estáticos
SPA <--> API : REST/JSON (API Gateway)
SPA --> ViaCEP : GET /ws/{cep}/json/

API --> DB : JDBC (Pool de Conexão)
API --> Fila : AMQPS (Producer)
Fila --> Worker : Push Event/ACK (Consumer)
Worker --> DB : JTA (Transaction)

@enduml